# Generated by Django 5.2.13 on 2026-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentprofile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='language',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.CharField(max_length=200),
        ),
    ]
