# Generated by Django 5.2.13 on 2026-05-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='education',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='experience',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('passing_year', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='student.studentprofile')),
            ],
        ),
    ]
