# Generated by Django 5.2.13 on 2026-05-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentprofile_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='education',
        ),
    ]
