# Generated by Django 5.2.13 on 2026-05-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studentprofile_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('salary', models.FloatField()),
                ('job_profile', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='college',
        ),
        migrations.RemoveField(
            model_name='education',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='education',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='education',
            name='university',
        ),
        migrations.AddField(
            model_name='education',
            name='board_university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education_type',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation')], default='Graduation', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='marks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.DateField(),
        ),
    ]
