# Generated by Django 5.2.13 on 2026-05-13 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_experience_remove_education_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='course',
        ),
        migrations.RemoveField(
            model_name='education',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='education',
            name='studuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='stud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
