# Generated by Django 5.2.13 on 2026-05-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_education_passing_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
