# Generated by Django 5.2.13 on 2026-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='no_of_employees',
            field=models.CharField(choices=[('1', '1-50'), ('2', '51-200'), ('3', '201-500'), ('4', 'More than 500')], max_length=200),
        ),
    ]
